#!/bin/bash

###############################################################################
# AUTOMATED BACKUP SETUP SCRIPT
# Purpose: Set up daily and weekly automated backups
# Usage: sudo bash 6_backup_setup.sh
# Author: Simux Tech
###############################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}================================${NC}"
echo -e "${GREEN}AUTOMATED BACKUP SETUP${NC}"
echo -e "${GREEN}================================${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Please run as root (use sudo)${NC}"
    exit 1
fi

# Configuration
BACKUP_DIR="/var/backups/server"
RETENTION_DAYS=7
RETENTION_WEEKS=4

echo -e "${YELLOW}Backup Configuration:${NC}"
echo "  Backup directory: $BACKUP_DIR"
echo "  Daily retention: $RETENTION_DAYS days"
echo "  Weekly retention: $RETENTION_WEEKS weeks"
echo ""
read -p "Continue with these settings? (y/n): " CONFIRM

if [ "$CONFIRM" != "y" ]; then
    echo "Aborted."
    exit 0
fi

# Create backup directories
echo -e "${YELLOW}[1/6] Creating backup directories...${NC}"
mkdir -p $BACKUP_DIR/{daily,weekly,logs}
chmod 700 $BACKUP_DIR
echo -e "${GREEN}✓ Directories created${NC}"
echo ""

# Get list of databases
echo -e "${YELLOW}[2/6] Detecting databases...${NC}"
DATABASES=()

# Check for PostgreSQL
if command -v psql &> /dev/null; then
    echo "PostgreSQL detected"
    read -p "Enter PostgreSQL database name to backup (or press Enter to skip): " PG_DB
    if [ -n "$PG_DB" ]; then
        read -p "Enter PostgreSQL username: " PG_USER
        DATABASES+=("postgres:$PG_DB:$PG_USER")
    fi
fi

# Check for MySQL/MariaDB
if command -v mysql &> /dev/null; then
    echo "MySQL/MariaDB detected"
    read -p "Enter MySQL database name to backup (or press Enter to skip): " MYSQL_DB
    if [ -n "$MYSQL_DB" ]; then
        read -p "Enter MySQL username: " MYSQL_USER
        read -sp "Enter MySQL password: " MYSQL_PASS
        echo ""
        DATABASES+=("mysql:$MYSQL_DB:$MYSQL_USER:$MYSQL_PASS")
    fi
fi

# Get web directories to backup
echo ""
read -p "Enter web directories to backup (space-separated, e.g., /var/www /opt/apps): " WEB_DIRS

echo -e "${GREEN}✓ Configuration collected${NC}"
echo ""

# Create backup script
echo -e "${YELLOW}[3/6] Creating backup script...${NC}"
cat > /usr/local/bin/server-backup.sh << 'BACKUP_SCRIPT_EOF'
#!/bin/bash

###############################################################################
# SERVER BACKUP SCRIPT
# Auto-generated by backup setup
###############################################################################

# Configuration
BACKUP_DIR="/var/backups/server"
DATE=$(date +%Y%m%d-%H%M%S)
LOG_FILE="$BACKUP_DIR/logs/backup-$DATE.log"

# Function to log messages
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a $LOG_FILE
}

# Function to send error notification (customize as needed)
notify_error() {
    log "ERROR: $1"
    # Add email notification here if configured
}

log "========================================="
log "BACKUP STARTED"
log "========================================="

# Determine backup type (daily or weekly)
BACKUP_TYPE="daily"
if [ "$(date +%u)" -eq 7 ]; then
    BACKUP_TYPE="weekly"
fi

BACKUP_PATH="$BACKUP_DIR/$BACKUP_TYPE/backup-$DATE"
mkdir -p $BACKUP_PATH

log "Backup type: $BACKUP_TYPE"
log "Backup path: $BACKUP_PATH"

# Backup system configuration files
log "Backing up system configuration..."
mkdir -p $BACKUP_PATH/system
cp -r /etc/nginx $BACKUP_PATH/system/ 2>/dev/null || log "WARNING: Nginx config not found"
cp -r /etc/apache2 $BACKUP_PATH/system/ 2>/dev/null || log "WARNING: Apache config not found"
cp /etc/hosts $BACKUP_PATH/system/ 2>/dev/null
cp /etc/crontab $BACKUP_PATH/system/ 2>/dev/null
crontab -l > $BACKUP_PATH/system/user-crontab.txt 2>/dev/null || log "No user crontab"

BACKUP_SCRIPT_EOF

# Add database backup commands
for db_config in "${DATABASES[@]}"; do
    IFS=':' read -r db_type db_name db_user db_pass <<< "$db_config"
    
    if [ "$db_type" = "postgres" ]; then
        cat >> /usr/local/bin/server-backup.sh << BACKUP_SCRIPT_EOF

# Backup PostgreSQL database: $db_name
log "Backing up PostgreSQL database: $db_name..."
mkdir -p \$BACKUP_PATH/databases
sudo -u postgres pg_dump $db_name > \$BACKUP_PATH/databases/${db_name}-postgres.sql 2>> \$LOG_FILE
if [ \$? -eq 0 ]; then
    gzip \$BACKUP_PATH/databases/${db_name}-postgres.sql
    log "✓ PostgreSQL backup completed"
else
    notify_error "PostgreSQL backup failed for $db_name"
fi
BACKUP_SCRIPT_EOF
    elif [ "$db_type" = "mysql" ]; then
        cat >> /usr/local/bin/server-backup.sh << BACKUP_SCRIPT_EOF

# Backup MySQL database: $db_name
log "Backing up MySQL database: $db_name..."
mkdir -p \$BACKUP_PATH/databases
mysqldump -u $db_user -p'$db_pass' $db_name > \$BACKUP_PATH/databases/${db_name}-mysql.sql 2>> \$LOG_FILE
if [ \$? -eq 0 ]; then
    gzip \$BACKUP_PATH/databases/${db_name}-mysql.sql
    log "✓ MySQL backup completed"
else
    notify_error "MySQL backup failed for $db_name"
fi
BACKUP_SCRIPT_EOF
    fi
done

# Add web directory backups
for dir in $WEB_DIRS; do
    cat >> /usr/local/bin/server-backup.sh << BACKUP_SCRIPT_EOF

# Backup directory: $dir
if [ -d "$dir" ]; then
    log "Backing up directory: $dir..."
    tar -czf \$BACKUP_PATH/$(basename $dir).tar.gz $dir 2>> \$LOG_FILE
    if [ \$? -eq 0 ]; then
        log "✓ Directory backup completed: $dir"
    else
        notify_error "Directory backup failed: $dir"
    fi
else
    log "WARNING: Directory not found: $dir"
fi
BACKUP_SCRIPT_EOF
done

# Complete backup script
cat >> /usr/local/bin/server-backup.sh << 'BACKUP_SCRIPT_EOF'

# Get backup size
BACKUP_SIZE=$(du -sh $BACKUP_PATH | cut -f1)
log "Backup size: $BACKUP_SIZE"

# Cleanup old backups
log "Cleaning up old backups..."

# Remove daily backups older than RETENTION_DAYS
find $BACKUP_DIR/daily -type d -name "backup-*" -mtime +RETENTION_DAYS_PLACEHOLDER -exec rm -rf {} \; 2>/dev/null
log "✓ Old daily backups removed"

# Remove weekly backups older than RETENTION_WEEKS * 7 days
RETENTION_WEEKS_DAYS=$((RETENTION_WEEKS_PLACEHOLDER * 7))
find $BACKUP_DIR/weekly -type d -name "backup-*" -mtime +$RETENTION_WEEKS_DAYS -exec rm -rf {} \; 2>/dev/null
log "✓ Old weekly backups removed"

# Remove old logs (keep 30 days)
find $BACKUP_DIR/logs -name "backup-*.log" -mtime +30 -delete 2>/dev/null

log "========================================="
log "BACKUP COMPLETED SUCCESSFULLY"
log "========================================="

exit 0
BACKUP_SCRIPT_EOF

# Replace placeholders
sed -i "s/RETENTION_DAYS_PLACEHOLDER/$RETENTION_DAYS/g" /usr/local/bin/server-backup.sh
sed -i "s/RETENTION_WEEKS_PLACEHOLDER/$RETENTION_WEEKS/g" /usr/local/bin/server-backup.sh

chmod +x /usr/local/bin/server-backup.sh
echo -e "${GREEN}✓ Backup script created${NC}"
echo ""

# Create restore script
echo -e "${YELLOW}[4/6] Creating restore helper script...${NC}"
cat > /usr/local/bin/server-restore.sh << 'RESTORE_SCRIPT_EOF'
#!/bin/bash

###############################################################################
# SERVER RESTORE HELPER SCRIPT
###############################################################################

BACKUP_DIR="/var/backups/server"

echo "Available backups:"
echo ""
echo "DAILY BACKUPS:"
ls -lth $BACKUP_DIR/daily/ 2>/dev/null | tail -n +2 | head -10
echo ""
echo "WEEKLY BACKUPS:"
ls -lth $BACKUP_DIR/weekly/ 2>/dev/null | tail -n +2 | head -5
echo ""
echo "To restore a backup:"
echo "1. Navigate to the backup directory"
echo "2. Extract files manually with: tar -xzf filename.tar.gz"
echo "3. Restore databases with: "
echo "   PostgreSQL: psql dbname < backup.sql"
echo "   MySQL: mysql -u user -p dbname < backup.sql"
echo ""
RESTORE_SCRIPT_EOF

chmod +x /usr/local/bin/server-restore.sh
echo -e "${GREEN}✓ Restore helper created${NC}"
echo ""

# Set up cron jobs
echo -e "${YELLOW}[5/6] Setting up cron jobs...${NC}"

# Remove old backup cron jobs if they exist
crontab -l 2>/dev/null | grep -v "server-backup.sh" | crontab - 2>/dev/null || true

# Add new cron job (daily at 2 AM)
(crontab -l 2>/dev/null; echo "0 2 * * * /usr/local/bin/server-backup.sh >> /var/backups/server/logs/cron.log 2>&1") | crontab -

echo -e "${GREEN}✓ Cron job added (runs daily at 2 AM)${NC}"
echo ""

# Run initial backup
echo -e "${YELLOW}[6/6] Running initial backup...${NC}"
echo "This may take a few minutes depending on data size..."
/usr/local/bin/server-backup.sh

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Initial backup completed${NC}"
else
    echo -e "${RED}Error: Initial backup failed${NC}"
    echo "Check logs at: $BACKUP_DIR/logs/"
fi
echo ""

# Summary
echo -e "${GREEN}================================${NC}"
echo -e "${GREEN}BACKUP SETUP COMPLETE!${NC}"
echo -e "${GREEN}================================${NC}"
echo ""
echo -e "Configuration:"
echo -e "  ✓ Automated daily backups at 2 AM"
echo -e "  ✓ Weekly backups every Sunday"
echo -e "  ✓ Daily retention: $RETENTION_DAYS days"
echo -e "  ✓ Weekly retention: $RETENTION_WEEKS weeks"
echo ""
echo -e "What's being backed up:"
if [ ${#DATABASES[@]} -gt 0 ]; then
    echo -e "  ✓ Databases (${#DATABASES[@]})"
fi
if [ -n "$WEB_DIRS" ]; then
    echo -e "  ✓ Web directories"
fi
echo -e "  ✓ System configurations"
echo ""
echo -e "${YELLOW}Useful Commands:${NC}"
echo ""
echo -e "Run manual backup:"
echo -e "  ${GREEN}sudo /usr/local/bin/server-backup.sh${NC}"
echo ""
echo -e "View available backups:"
echo -e "  ${GREEN}sudo /usr/local/bin/server-restore.sh${NC}"
echo -e "  ${GREEN}sudo ls -lh $BACKUP_DIR/daily/${NC}"
echo -e "  ${GREEN}sudo ls -lh $BACKUP_DIR/weekly/${NC}"
echo ""
echo -e "View backup logs:"
echo -e "  ${GREEN}sudo tail -f $BACKUP_DIR/logs/backup-*.log${NC}"
echo -e "  ${GREEN}sudo cat $BACKUP_DIR/logs/cron.log${NC}"
echo ""
echo -e "Restore a database:"
echo -e "  PostgreSQL: ${GREEN}sudo -u postgres psql dbname < backup.sql${NC}"
echo -e "  MySQL: ${GREEN}mysql -u user -p dbname < backup.sql${NC}"
echo ""
echo -e "Check cron jobs:"
echo -e "  ${GREEN}crontab -l${NC}"
echo ""
echo -e "${YELLOW}Backup locations:${NC}"
echo -e "  Daily: $BACKUP_DIR/daily/"
echo -e "  Weekly: $BACKUP_DIR/weekly/"
echo -e "  Logs: $BACKUP_DIR/logs/"
echo ""
echo -e "${RED}⚠ IMPORTANT:${NC}"
echo -e "1. Consider storing backups off-site (S3, another VPS, etc.)"
echo -e "2. Test your restore process regularly"
echo -e "3. Monitor backup logs to ensure backups succeed"
echo -e "4. Backup directory size will grow - monitor disk space"
echo ""
echo -e "${YELLOW}NEXT STEPS:${NC}"
echo -e "1. Run: sudo bash 7_monitoring_setup.sh"
echo -e "2. Set up remote backup storage (optional)"
echo -e "3. Test restore process"
echo ""
